import type { Chat } from '../shared/chat.ts'

/** Public chats snapshotted from t.me. Search refreshes the top matches live. */
export const catalog: Chat[] = [
  {
    "username": "telegramtips",
    "title": "Telegram Tips",
    "description": "Telegram stands for freedom and privacy and has many easy to use features.",
    "type": "channel",
    "category": "Official",
    "language": "en",
    "members": 10906271,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/telegramtips",
    "source": "catalog",
    "live": false
  },
  {
    "username": "durov",
    "title": "Pavel Durov",
    "description": "Founder of Telegram.",
    "type": "channel",
    "category": "Official",
    "language": "en",
    "members": 10611658,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/durov",
    "source": "catalog",
    "live": false
  },
  {
    "username": "telegram",
    "title": "Telegram News",
    "description": "The official Telegram on Telegram. Much recursion. Very Telegram. Wow.",
    "type": "channel",
    "category": "Official",
    "language": "en",
    "members": 9457679,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/telegram",
    "source": "catalog",
    "live": false
  },
  {
    "username": "premium",
    "title": "Telegram Premium",
    "description": "Telegram Premium – a subscription that unlocks dozens of exclusive features.",
    "type": "channel",
    "category": "Official",
    "language": "en",
    "members": 6547288,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/premium",
    "source": "catalog",
    "live": false
  },
  {
    "username": "toporlive",
    "title": "Топор Live",
    "description": "Нейтрально, без пропаганды. Топор Live с быстрыми новостями. Новости присылать сюда: @Toporchan_Bot Наш канал без цензуры – https://t.me/+3sUd12FqwxliYWY6 По всем вопросам: @toporch РКН: https://gosuslugi.ru/snet/686b87224b40c72af9b5370c",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 4105571,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/toporlive",
    "source": "catalog",
    "live": false
  },
  {
    "username": "binance_announcements",
    "title": "Binance Announcements",
    "description": "Binance Official English Group @binanceexchange Binance Official Chinese Group @BinanceChinese Binance English Announcements @binance_announcements Binance Chinese Announcements @binance_cn",
    "type": "channel",
    "category": "Crypto",
    "language": "en",
    "members": 3409430,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/binance_announcements",
    "source": "catalog",
    "live": false
  },
  {
    "username": "breakingmash",
    "title": "Mash",
    "description": "Прислать новость, фото, видео: @inmash1_bot По вопросам рекламы @marina_mousse Помахаться и обсудить новости: t.me/masx3_0 Регистрация в перечне РКН: https://knd.gov.ru/license?id=6726d0b5db0c1931b12fc77f&registryType=bloggersPermission",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 3109892,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/breakingmash",
    "source": "catalog",
    "live": false
  },
  {
    "username": "mash",
    "title": "Mash",
    "description": "Прислать новость, фото, видео: @inmash1_bot По вопросам рекламы @marina_mousse Помахаться и обсудить новости: t.me/masx3_0 Регистрация в перечне РКН: https://knd.gov.ru/license?id=6726d0b5db0c1931b12fc77f&registryType=bloggersPermission",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 3109892,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/mash",
    "source": "catalog",
    "live": false
  },
  {
    "username": "rian_ru",
    "title": "РИА Новости",
    "description": "Главные Новости РИА Авторы канала - наши корреспонденты в России и за рубежом. Мы рассказываем о том, что видим сами. Регистрация в перечне РКН www.gosuslugi.ru/snet/678637f9506f967728faabaa",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 3040557,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/rian_ru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "readovkanews",
    "title": "Readovka",
    "description": "Важное — собранное вместе. Главное — разобранное на смыслы. Прислать новость: @readovka_novosti Реклама: @zareadovka Коммерческая служба: +7 917 529 0962 Разбан в чате: @moderReadovka",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 2013499,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/readovkanews",
    "source": "catalog",
    "live": false
  },
  {
    "username": "bazabazon",
    "title": "Baza",
    "description": "Предложка: @Baza_predlozhka Реклама: @advert_newsmedia Регистрация в РКН: https://knd.gov.ru/license?id=676d14dc8e552d6b542963cd&registryType=bloggersPermission",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 1564983,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/bazabazon",
    "source": "catalog",
    "live": false
  },
  {
    "username": "topor",
    "title": "ТОПОР - Горячие новости",
    "description": "Новости присылать сюда: @Toporchan_Bot Наш канал без цензуры 18+: https://t.me/joinchat/ScL1FOCgJCbFNJK1 Live канал: https://t.me/+n0B2XbLYjbMwMDEy По всем вопросам @toporch",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 1295672,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/topor",
    "source": "catalog",
    "live": false
  },
  {
    "username": "shot_shot",
    "title": "SHOT",
    "description": "Самый цитируемый телеграм-канал России Для связи: @shot_go Реклама: @advert_newsmedia SHOT Проверка: https://t.me/+HFoegHAB6JMzYmU6 Регистрация в перечне РКН: https://knd.gov.ru/license?id=6726d386aee8a56e0fdd5706&registryType=bloggersPermission",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 1265239,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/shot_shot",
    "source": "catalog",
    "live": false
  },
  {
    "username": "meduzalive",
    "title": "Медуза — LIVE",
    "description": "Главный телеграм-канал «Медузы». Для связи: @m_needs_you Приложение для iOS https://mdza.io/JtSJ9t50Ww4 И для Android https://mdza.io/IQkzDh0RHw4",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 1122208,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/meduzalive",
    "source": "catalog",
    "live": false
  },
  {
    "username": "varlamov_news",
    "title": "Varlamov News",
    "description": "• новостной канал от @varlamov • связь через https://t.me/varlamov_news?direct • срочные новости: @varlamovbrkng • YouTube: https://vrlmv.com/QoIGMN • другие соцсети: links.varlamov.ru/p/6a18e2/ • продаем рекламу: ads@varlamov.me",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 1061154,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/varlamov_news",
    "source": "catalog",
    "live": false
  },
  {
    "username": "rbc_news",
    "title": "РБК. Новости. Главное",
    "description": "Официальный канал РБК. Самые важные новости, только проверенная информация. По вопросам рекламы - @rbctgadv , reklamatg@rbc.ru Прислать новость, фото или видео: @rbc_reporter_bot Регистрация в РКН: https://clck.ru/3SjuLB",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 914252,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/rbc_news",
    "source": "catalog",
    "live": false
  },
  {
    "username": "rozetked",
    "title": "Rozetked",
    "description": "Текстом и видео о мире, технологиях, медиакультуре и не только. rozetked.me youtube.com/rozetked Реклама: @d_garaschenko (каналы не рекламируем) Предложить новость: @rozetkednewsbot Реестр РКН: clck.ru/3F4n3w",
    "type": "channel",
    "category": "Tech",
    "language": "ru",
    "members": 674511,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/rozetked",
    "source": "catalog",
    "live": false
  },
  {
    "username": "match_tv",
    "title": "Матч ТВ",
    "description": "Третья кнопка твоего телевизора в телеграме Все наши каналы: https://t.me/addlist/Hhiq_3EbCJcyMjIy № 4790210908",
    "type": "channel",
    "category": "Sports",
    "language": "ru",
    "members": 668939,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/match_tv",
    "source": "catalog",
    "live": false
  },
  {
    "username": "tass_agency",
    "title": "ТАСС",
    "description": "Главные новости агентства ТАСС https://tass.ru Регистрация в перечне РКН: https://knd.gov.ru/license?id=673f0f77290fef0e012d86a9&registryType=bloggersPermission",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 568301,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/tass_agency",
    "source": "catalog",
    "live": false
  },
  {
    "username": "sportsru",
    "title": "Спортс“",
    "description": "Лучший спортивный телеграм 🐐 Наши каналы: https://t.me/sportsru/105292 Приложение: https://apps.sports.ru 📩 Реклама: sales@sports.ru 🧳 Вакансии: @career_sports 📲 Обмены: @feed_back_sportsru_bot 🎮 Игры: t.me/SirenaSpecBot?startapp № 4786262530",
    "type": "channel",
    "category": "Sports",
    "language": "ru",
    "members": 437911,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/sportsru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "ostorozhno_moskva",
    "title": "Осторожно, Москва",
    "description": "связаться с редакцией/ предложить новость: @moskva_ostorozhno_bot дубль канала в MAX: https://max.ru/ostorozhno_moskva перечень ркн: https://gosuslugi.ru/snet/67a5caa4a16f1b5542a3c875",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 392889,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/ostorozhno_moskva",
    "source": "catalog",
    "live": false
  },
  {
    "username": "bbcrussian",
    "title": "BBC News | Русская служба",
    "description": "Официальный канал Русской службы Би-би-си Ньюз https://www.bbc.com/russian",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 387883,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/bbcrussian",
    "source": "catalog",
    "live": false
  },
  {
    "username": "lentadnya",
    "title": "Лента дня",
    "description": "В основном новости. Lenta.ru По рекламе и сотрудничеству — @smirnoffkan Проверено @TgPodbor_bot Предложка — @Lentadnya_connectbot Мы в Max — max.ru/lentaru Регистрация в перечне РКН: https://lenta.ru/go/hvqb/",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 355307,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/lentadnya",
    "source": "catalog",
    "live": false
  },
  {
    "username": "cointelegraph",
    "title": "Cointelegraph",
    "description": "The Future of Money Unbiased crypto, markets & Web3 news in real-time. Trusted since 2013. 🔔 Turn on notifications to catch the calls that move markets. Explore: linktr.ee/cointelegraph_mobile For ads: advertise@cointelegraph.com",
    "type": "channel",
    "category": "Crypto",
    "language": "en",
    "members": 333719,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/cointelegraph",
    "source": "catalog",
    "live": false
  },
  {
    "username": "dota2",
    "title": "Dota 2",
    "description": "🐉 Логово дотеров — новости, гайды, баги, фишки, расписание матчей и розыгрыши! 🏆 Один клик и лучшие каналы у тебя в папке: https://t.me/addlist/kAcAvmMEc1c0NDlk 🔖 Разместить рекламу: @reklama_nikita",
    "type": "channel",
    "category": "Games",
    "language": "ru",
    "members": 315275,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/dota2",
    "source": "catalog",
    "live": false
  },
  {
    "username": "contest",
    "title": "Telegram Contests",
    "description": "Here we announce Telegram coding contests in Android Java, iOS Swift, JS, C/C++. Discussion: @contests",
    "type": "channel",
    "category": "Official",
    "language": "en",
    "members": 298957,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/contest",
    "source": "catalog",
    "live": false
  },
  {
    "username": "kommersant",
    "title": "Коммерсантъ",
    "description": "Официальный канал ИД «Коммерсантъ». Новости бизнеса, финансов, политики, общества, культуры и спорта. Обратная связь: kommersant.ru/lk/feedback По вопросам рекламы: rr@kommersant.ru Перечень РКН: https://clck.ru/3FFxpT",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 294419,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/kommersant",
    "source": "catalog",
    "live": false
  },
  {
    "username": "getgems",
    "title": "Getgems NFT",
    "description": "getgems.io — the Home of NFT collections on The Open Network - an ultra-fast, secure, and truly decentralized blockchain network. Twitter: https://twitter.com/getgemsdotio Support: @nfton_bot",
    "type": "channel",
    "category": "Crypto",
    "language": "en",
    "members": 270433,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/getgems",
    "source": "catalog",
    "live": false
  },
  {
    "username": "championat",
    "title": "Чемпионат",
    "description": "Главное слово в спорте — championat.com Новости, инсайды, экспертиза. Канал проверен @TgPodbor_bot По рекламе – @smirnoffkan Маркетинговые партнёрства — @champ_friends_bot РКН: https://gosuslugi.ru/snet/67937a3c19290c0f936787b4",
    "type": "channel",
    "category": "Sports",
    "language": "ru",
    "members": 249568,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/championat",
    "source": "catalog",
    "live": false
  },
  {
    "username": "varlamov",
    "title": "Илья Варламов",
    "description": "Соцсети и YouTube: links.varlamov.ru/p/6a1270",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 236621,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/varlamov",
    "source": "catalog",
    "live": false
  },
  {
    "username": "nytimes",
    "title": "The New York Times",
    "description": "New York Times coverage from around the world, including the Russia-Ukraine war. Get the latest at https://www.nytimes.com/world",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 184035,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/nytimes",
    "source": "catalog",
    "live": false
  },
  {
    "username": "bloomberg",
    "title": "Bloomberg",
    "description": "The first word in business news.",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 180646,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/bloomberg",
    "source": "catalog",
    "live": false
  },
  {
    "username": "currenttime",
    "title": "Настоящее Время",
    "description": "Бот для связи с редакцией: @safe_contact_bot Почта: info@currenttime.tv Как читать нас из России: https://smarturl.click/3MQp",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 145280,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/currenttime",
    "source": "catalog",
    "live": false
  },
  {
    "username": "tradingview",
    "title": "TradingView",
    "description": "This is TradingView’s official Telegram. Subscribe for tips, wisdom, education, and market-moving charts. Look first / then leap.",
    "type": "channel",
    "category": "Finance",
    "language": "en",
    "members": 141036,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/tradingview",
    "source": "catalog",
    "live": false
  },
  {
    "username": "habr_com",
    "title": "Хабр",
    "description": "НЛО с вами! № 5197888779 Хабр Новости → https://t.me/habr_com_news Хабр Карьера → https://t.me/habr_career Реклама → adv@habr.team",
    "type": "channel",
    "category": "Tech",
    "language": "ru",
    "members": 132718,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/habr_com",
    "source": "catalog",
    "live": false
  },
  {
    "username": "botnews",
    "title": "BotNews",
    "description": "The official source for news about the Telegram Bot API. https://core.telegram.org/bots",
    "type": "channel",
    "category": "Official",
    "language": "en",
    "members": 131613,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/botnews",
    "source": "catalog",
    "live": false
  },
  {
    "username": "science",
    "title": "Science in telegram",
    "description": "Science that matters: AI, space, biotech, physics, future tech — explained sharply",
    "type": "channel",
    "category": "Science",
    "language": "en",
    "members": 120211,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/science",
    "source": "catalog",
    "live": false
  },
  {
    "username": "themes",
    "title": "Desktop Themes Channel",
    "description": "Desktop Themes for all! If you'd like to see your Desktop theme featured here or learn how to make your own, join our Desktop Themes group (t.me/TelegramThemes). Want other cool themes? - https://telegra.ph/Telegram-Themes-Library-05-06",
    "type": "channel",
    "category": "Official",
    "language": "en",
    "members": 120008,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/themes",
    "source": "catalog",
    "live": false
  },
  {
    "username": "dota2news",
    "title": "НОВОСТИ DOTA 2",
    "description": "Неофициальное сообщество Дота 2 🥭 Реклама: @mmango • ютуб: youtube.com/@mangodota2 • тикток: tiktok.com/@mangodota • агенты: @spiral_yuri , @oldpurple , @nikosrythm , @reklama_nikita , @mmango",
    "type": "channel",
    "category": "Games",
    "language": "ru",
    "members": 107716,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/dota2news",
    "source": "catalog",
    "live": false
  },
  {
    "username": "radiosvoboda",
    "title": "Радио Свобода / Radio Svoboda (ru)",
    "description": "Радио Свобода – «нежелательная организация». Вы можете спокойно читать, смотреть и слушать нас, даже если находитесь в России. Но помните о своей безопасности: возможно, вы решите воздержаться от комментов и лайков. Поделитесь новостью @svobodaradiobot",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 102064,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/radiosvoboda",
    "source": "catalog",
    "live": false
  },
  {
    "username": "python",
    "title": "Python",
    "description": "You will be muted until you read the rules. Read them! @Rules_for_Python A group about the Python programming language. Offtopic things go here: @pythonofftopic Resources to learn python: @pythonres Group for Hy: @hylang Selenium: @SeleniumPython",
    "type": "group",
    "category": "Community",
    "language": "en",
    "members": 95451,
    "online": 4445,
    "verified": false,
    "photo": null,
    "link": "https://t.me/python",
    "source": "catalog",
    "live": false
  },
  {
    "username": "memes",
    "title": "Memes™ 🎄 2014",
    "description": "This channel is sponsored by stolen memes.",
    "type": "channel",
    "category": "Entertainment",
    "language": "en",
    "members": 85071,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/memes",
    "source": "catalog",
    "live": false
  },
  {
    "username": "proglib",
    "title": "Библиотека программиста",
    "description": "Все самое полезное для программиста в одном канале. Наши курсы: https://clc.to/Jil6fg По рекламе: @tproger_sales_bot Для обратной связи: @proglibrary_feeedback_bot РКН: https://gosuslugi.ru/snet/67a5ba2901234b69883a4d46 Заявка: 8137611477",
    "type": "channel",
    "category": "Tech",
    "language": "ru",
    "members": 78262,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/proglib",
    "source": "catalog",
    "live": false
  },
  {
    "username": "tproger",
    "title": "Типичный программист",
    "description": "Всё самое интересное по программированию Разместить рекламу: @tproger_sales_bot Правила общения: https://tprg.ru/rules Другие каналы: @tproger_channels Сайт: https://tprg.ru/site VK: vk.com/tproger Регистрация в перечне РКН: https://tprg.ru/mJwo",
    "type": "channel",
    "category": "Tech",
    "language": "ru",
    "members": 78228,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/tproger",
    "source": "catalog",
    "live": false
  },
  {
    "username": "photoshop",
    "title": "Photoshop Tutorial",
    "description": "➣ FREE Premium Tutorial ➣ Support: @ads_operator ➣ Legal advertising: https://telega.io/c/photoshop",
    "type": "channel",
    "category": "Design",
    "language": "en",
    "members": 75728,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/photoshop",
    "source": "catalog",
    "live": false
  },
  {
    "username": "nature",
    "title": "Nature 🌎",
    "description": "International Nature channel. Discover Earth with us! Chat: @natureschat",
    "type": "channel",
    "category": "Science",
    "language": "en",
    "members": 74718,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/nature",
    "source": "catalog",
    "live": false
  },
  {
    "username": "addmeto",
    "title": "addmeto",
    "description": "Только интересные новости из мира IT и технологий, со ссылками на англоязычные источники. Единственный автор @bobuk . Рекламы в канале нет (и не просите). Правила общения в коментариях bit.ly/reasonable-default",
    "type": "channel",
    "category": "Tech",
    "language": "ru",
    "members": 71836,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/addmeto",
    "source": "catalog",
    "live": false
  },
  {
    "username": "deeplearning_ai",
    "title": "Artificial Intelligence && Deep Learning",
    "description": "Channel for who have a passion for - * Artificial Intelligence * Machine Learning * Deep Learning * Data Science * Computer vision * Image Processing * Research Papers With advertising offers contact:",
    "type": "channel",
    "category": "Tech",
    "language": "en",
    "members": 57412,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/deeplearning_ai",
    "source": "catalog",
    "live": false
  },
  {
    "username": "washingtonpost",
    "title": "The Washington Post",
    "description": "The official Washington Post channel, sharing live news coverage of Russia’s war in Ukraine. You can find our full coverage at https://www.washingtonpost.com/world/ukraine-russia/. The Post’s coverage is free to access in Ukraine and Russia.",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 57047,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/washingtonpost",
    "source": "catalog",
    "live": false
  },
  {
    "username": "inter",
    "title": "inter",
    "description": "Canale ufficiale di FC Internazionale Milano 🔵⚫️ fb.com/inter | twitter.com/inter | youtube.com/inter | https://inter.it",
    "type": "channel",
    "category": "Sports",
    "language": "it",
    "members": 54599,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/inter",
    "source": "catalog",
    "live": false
  },
  {
    "username": "motogp",
    "title": "MotoGP",
    "description": "The official Telegram channel of MotoGP™! Faster. Forward. Fearless",
    "type": "channel",
    "category": "Sports",
    "language": "en",
    "members": 48425,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/motogp",
    "source": "catalog",
    "live": false
  },
  {
    "username": "formula1",
    "title": "Formula1",
    "description": "Formula 1 Live Feedback: @F1fb_bot",
    "type": "channel",
    "category": "Sports",
    "language": "en",
    "members": 47292,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/formula1",
    "source": "catalog",
    "live": false
  },
  {
    "username": "glassnode",
    "title": "Glassnode",
    "description": "Institutional Data and Market Intelligence for Digital Assets. https://studio.glassnode.com/",
    "type": "channel",
    "category": "Crypto",
    "language": "en",
    "members": 44140,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/glassnode",
    "source": "catalog",
    "live": false
  },
  {
    "username": "guardian",
    "title": "The Guardian",
    "description": "Latest coverage of the Russia-Ukraine war",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 41657,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/guardian",
    "source": "catalog",
    "live": false
  },
  {
    "username": "tjournal",
    "title": "TJ",
    "description": "Самые обсуждаемые новости дня. Канал ведёт редакция TJ. Связаться с нами: editors@tjournal.ru Разместить рекламу: sales@cmtt.ru tjournal.ru",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 35746,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/tjournal",
    "source": "catalog",
    "live": false
  },
  {
    "username": "appleinsider",
    "title": "AppleInsider.ru #новости",
    "description": "Официальный канал сайта AppleInsider.ru Реклама - advert@i10.ru",
    "type": "channel",
    "category": "Tech",
    "language": "ru",
    "members": 34228,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/appleinsider",
    "source": "catalog",
    "live": false
  },
  {
    "username": "bbcbrasil",
    "title": "BBC News Brasil",
    "description": "Canal oficial de transmissão de notícias da BBC News Brasil.",
    "type": "channel",
    "category": "News",
    "language": "pt",
    "members": 34037,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/bbcbrasil",
    "source": "catalog",
    "live": false
  },
  {
    "username": "javascript",
    "title": "JavaScript",
    "description": "A resourceful newsletter featuring the latest and most important news, articles, books and updates in the world of #javascript 🚀 Don't miss our Quizzes! Let's chat: @nairihar",
    "type": "channel",
    "category": "Tech",
    "language": "en",
    "members": 31115,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/javascript",
    "source": "catalog",
    "live": false
  },
  {
    "username": "iguides",
    "title": "iGuides.ru",
    "description": "Самые актуальные новости из мира гаджетов и технологий. В нашей ленте вы найдете: обзоры, личный опыт, инструкции. Мы каждый день держим руку на пульсе актуальных тем: нейросети, приложения, сервисы, автомобили и поп-культура.",
    "type": "channel",
    "category": "Tech",
    "language": "ru",
    "members": 30100,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/iguides",
    "source": "catalog",
    "live": false
  },
  {
    "username": "desktop",
    "title": "Telegram Desktop",
    "description": "The official Telegram Desktop channel, firsthand information from the developer. https://desktop.telegram.org",
    "type": "channel",
    "category": "Official",
    "language": "en",
    "members": 28171,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/desktop",
    "source": "catalog",
    "live": false
  },
  {
    "username": "javascript_jobs",
    "title": "JavaScript Jobs — чат",
    "description": "JavaScript Jobs — чат для поиска работы и людей Правила оформления в закрепленном сообщении",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 27560,
    "online": 5974,
    "verified": false,
    "photo": null,
    "link": "https://t.me/javascript_jobs",
    "source": "catalog",
    "live": false
  },
  {
    "username": "cnnbrasil",
    "title": "CNN BRASIL",
    "description": "Siga os últimos fatos da política, economia e internacional, no maior canal de notícias do mundo. Breaking news, análises e vídeos",
    "type": "channel",
    "category": "News",
    "language": "pt",
    "members": 26853,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/cnnbrasil",
    "source": "catalog",
    "live": false
  },
  {
    "username": "csgo",
    "title": "Новости CS2 | @CSGO",
    "description": "Веду авторский блог про Counter-Strike 2 и киберспорт в формате без лица и без цензуры. Для вас - рофлы, розыгрыши, интерактивы и мой вайб. Отзывы победителей - @csgorafflewinners Предложка - @CS2ibot CS:GO в ❤️",
    "type": "channel",
    "category": "Games",
    "language": "ru",
    "members": 26112,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/csgo",
    "source": "catalog",
    "live": false
  },
  {
    "username": "france24_en",
    "title": "FRANCE 24 English",
    "description": "The French international news channel live 24/7 from Paris Follow us for top stories on #business, #politics and #sports. 🌍 france24.com/en/",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 24745,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/france24_en",
    "source": "catalog",
    "live": false
  },
  {
    "username": "devops_ru",
    "title": "DevOps — русскоговорящее сообщество",
    "description": "Общаемся на темы DevOps, мониторинга, метрикам и облакам. Новости. См. также: @kubernetes_ru , @docker_ru , @ceph_ru , @openstack_ru FAQ и правила: https://git.io/JtnWb Вакансии и поиск работы: @devops_jobs",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 20590,
    "online": 4193,
    "verified": false,
    "photo": null,
    "link": "https://t.me/devops_ru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "skynews",
    "title": "Sky News",
    "description": "The best of Sky News breaking news, eyewitness journalism, and video. On TikTok here: https://vm.tiktok.com/ZMLsHV537/ and on YouTube here: https://youtube.com/c/SkyNews",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 20470,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/skynews",
    "source": "catalog",
    "live": false
  },
  {
    "username": "photography",
    "title": "photography",
    "description": "FolkFrame Photography Independent Photography Media & Community Stories Begin With a Frame. For photo submissions, please see the pinned post. Contact us @Peyman404",
    "type": "channel",
    "category": "Entertainment",
    "language": "en",
    "members": 20347,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/photography",
    "source": "catalog",
    "live": false
  },
  {
    "username": "golang",
    "title": "Go",
    "description": "// admin @denniselite // Denis Podlesnykh, a Golang Engineer go func() { channel <- news }() news := <-channel fmt.Sprintf(\"%s\", news)",
    "type": "channel",
    "category": "Tech",
    "language": "en",
    "members": 19310,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/golang",
    "source": "catalog",
    "live": false
  },
  {
    "username": "elpais",
    "title": "ELPAÍS",
    "description": "La mejor información en español. Con nuestra mirada puesta en España, Europa y América. elpais.com",
    "type": "channel",
    "category": "News",
    "language": "es",
    "members": 17850,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/elpais",
    "source": "catalog",
    "live": false
  },
  {
    "username": "aljazeeraenglish",
    "title": "AL JAZEERA ENGLISH",
    "description": "",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 16749,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/aljazeeraenglish",
    "source": "catalog",
    "live": false
  },
  {
    "username": "figma",
    "title": "Figma",
    "description": "У Figma нет официальных сообществ и каналов на русском, поэтому своими силами рассказываю обо всех новостях подробно и без мусора ❤️ Вопросы задавай в Фигма-чат: @figmachat Группа ВК: https://vk.com/figmadesign",
    "type": "channel",
    "category": "Design",
    "language": "ru",
    "members": 16247,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/figma",
    "source": "catalog",
    "live": false
  },
  {
    "username": "btgpactual",
    "title": "BTG Pactual",
    "description": "Bem-vindo(a) ao canal oficial do BTG Pactual. Aqui você encontrará os melhores conteúdos relacionados ao mercado financeiro com análises, notícias e relatórios exclusivos. Abra sua conta: www.btgpactual.com",
    "type": "channel",
    "category": "Finance",
    "language": "pt",
    "members": 16204,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/btgpactual",
    "source": "catalog",
    "live": false
  },
  {
    "username": "ru_python",
    "title": "Python",
    "description": "Уютный чат для профессионалов, занимающихся поиском питоньих мудростей. Как не получить бан: https://t.me/ru_python/2755095",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 15955,
    "online": 2990,
    "verified": false,
    "photo": null,
    "link": "https://t.me/ru_python",
    "source": "catalog",
    "live": false
  },
  {
    "username": "spacex",
    "title": "SpaceX",
    "description": "(Unofficial) News and updates about the amazing space company that's leading humanity to the stars For more detailed updates and discussions join our chat: @SpaceXChat @SpaceXFeed ⛔️ No SpaceX crypto exists.",
    "type": "channel",
    "category": "Science",
    "language": "en",
    "members": 15413,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/spacex",
    "source": "catalog",
    "live": false
  },
  {
    "username": "tecnoblog",
    "title": "Tecnoblog",
    "description": "👨🏻‍💻 Tecnologia que interessa. As melhores notícias do TB estão aqui! Nos acompanhe em todos os canais: 📸 instagram.com/tecnoblog 📺 youtube.com/tecnoblog 🎬 tiktok.com/@tecnoblog 🐦 twitter.com/tecnoblog 🎧 wavve.link/tecnocast",
    "type": "channel",
    "category": "Tech",
    "language": "pt",
    "members": 14830,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/tecnoblog",
    "source": "catalog",
    "live": false
  },
  {
    "username": "infobae",
    "title": "Infobae",
    "description": "Todo el tiempo. Todas las noticias.",
    "type": "channel",
    "category": "News",
    "language": "es",
    "members": 14771,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/infobae",
    "source": "catalog",
    "live": false
  },
  {
    "username": "whale_alert",
    "title": "Whale Alert",
    "description": "Live tracking of large crypto transactions from and to exchanges and tether creations. Shows alerts for: #BTC, #ETH, #USDt, and top 100 #ERC20 tokens Mirrors tweets from: https://twitter.com/whale_alert",
    "type": "channel",
    "category": "Crypto",
    "language": "en",
    "members": 14251,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/whale_alert",
    "source": "catalog",
    "live": false
  },
  {
    "username": "qa_ru",
    "title": "QA — русскоговорящее сообщество",
    "description": "Общаемся про все виды тестирования и его автоматизацию. Без мата, грубостей и провокаций. События @qaevents Вакансии @qa_jobs Резюме @qa_resumes Автоматизация @qa_automation Флуд @qaflood За пиратский контент бан Админ всегда админ",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 13967,
    "online": 3441,
    "verified": false,
    "photo": null,
    "link": "https://t.me/qa_ru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "laravel",
    "title": "Laravel",
    "description": "» in the name of God Admin 👉 {!! @mehrabjafari !!} The domain larawel.com is for sale... @laravelCast @laravel_discuss",
    "type": "channel",
    "category": "Tech",
    "language": "en",
    "members": 12465,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/laravel",
    "source": "catalog",
    "live": false
  },
  {
    "username": "poder360",
    "title": "Poder360",
    "description": "Canal oficial do jornal digital Poder360",
    "type": "channel",
    "category": "News",
    "language": "pt",
    "members": 12088,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/poder360",
    "source": "catalog",
    "live": false
  },
  {
    "username": "django",
    "title": "Django",
    "description": "Telegram group for Django users. Django is a high-level Python Web framework (djangoproject.com). Rules from @Rules_for_Python apply here too, read them!",
    "type": "group",
    "category": "Community",
    "language": "en",
    "members": 11614,
    "online": 904,
    "verified": false,
    "photo": null,
    "link": "https://t.me/django",
    "source": "catalog",
    "live": false
  },
  {
    "username": "android_ru",
    "title": "Android Developers",
    "description": "Общаемся на темы, посвящённые нативной Android-разработке. + Про Android NDK: @ndk_ru + Про iOS: @ios_ru + Вакансии: @mobile_jobs + It чаты @it_chats + Флудилка @androidflood Рекомендуем отключить уведомления, чтобы пребывание было комфортным.",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 11171,
    "online": 2478,
    "verified": false,
    "photo": null,
    "link": "https://t.me/android_ru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "python_jobs",
    "title": "Python — вакансии и аналитика",
    "description": "Публикуем вакансии и запросы на поиск работы по направлению Python, Flask и т.д. Здесь всё: full-time, part-time, remote и разовые подработки. См. также: @golang_jobs , @qa_jobs , @devops_jobs , @javascript_jobs , @nodejs_jobs , @uiux_jobs , @products_jobs",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 8112,
    "online": 2029,
    "verified": false,
    "photo": null,
    "link": "https://t.me/python_jobs",
    "source": "catalog",
    "live": false
  },
  {
    "username": "clarincom",
    "title": "Clarín",
    "description": "Toda la información sobre la política nacional 🇦🇷",
    "type": "channel",
    "category": "News",
    "language": "es",
    "members": 7888,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/clarincom",
    "source": "catalog",
    "live": false
  },
  {
    "username": "estadao",
    "title": "Estadão",
    "description": "",
    "type": "channel",
    "category": "News",
    "language": "pt",
    "members": 7833,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/estadao",
    "source": "catalog",
    "live": false
  },
  {
    "username": "nodejs_ru",
    "title": "Node.js — русскоговорящее сообщество",
    "description": "Рекомендуем сразу отключить уведомления, чтобы пребывание здесь было комфортным. См. также: @js_ru , @react_js , @angular_ru , @vuejs_ru , @devops_ru Вакансии и поиск работы: @javascript_jobs и @nodejs_jobs Правила: https://t.me/nodejs_ru/1072444",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 7787,
    "online": 1961,
    "verified": false,
    "photo": null,
    "link": "https://t.me/nodejs_ru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "kotlin_lang",
    "title": "Kotlin Community",
    "description": "Сообщество разработчиков на Kotlin 💙 Kotlin Language users Community 💛 Rules, Info: https://t.me/kotlin_lang?topic=293404",
    "type": "group",
    "category": "Community",
    "language": "en",
    "members": 6831,
    "online": 1641,
    "verified": false,
    "photo": null,
    "link": "https://t.me/kotlin_lang",
    "source": "catalog",
    "live": false
  },
  {
    "username": "politico",
    "title": "Politico",
    "description": "Sharing the most important stories and updates affecting national security",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 6649,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/politico",
    "source": "catalog",
    "live": false
  },
  {
    "username": "folha",
    "title": "Folha de S.Paulo",
    "description": "Canal oficial da Folha de S.Paulo no Telegram",
    "type": "channel",
    "category": "News",
    "language": "pt",
    "members": 6223,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/folha",
    "source": "catalog",
    "live": false
  },
  {
    "username": "lentach",
    "title": "Настоящий Лентач",
    "description": "Пропаганда здравого смысла 18+ Реклама: @lisa_white",
    "type": "channel",
    "category": "News",
    "language": "ru",
    "members": 5043,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/lentach",
    "source": "catalog",
    "live": false
  },
  {
    "username": "leagueoflegends",
    "title": "League of Legends",
    "description": "League of Legends [UNOFFICIAL] Contact: @BHMTNetwork_Bot",
    "type": "channel",
    "category": "Games",
    "language": "en",
    "members": 4703,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/leagueoflegends",
    "source": "catalog",
    "live": false
  },
  {
    "username": "frontend_ru",
    "title": "Frontend_ru",
    "description": "Русскоговорящее сообщество фронтенд разработчиков Каналы: @frontendnoteschannel @defront Чаты: @bem_ru @javascript_ru @css_ru Важно! http://nometa.xyz",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 3334,
    "online": 643,
    "verified": false,
    "photo": null,
    "link": "https://t.me/frontend_ru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "manualdousuario",
    "title": "Manual do Usuário",
    "description": "Comentários de tecnologia. https://www.manualdousuario.net",
    "type": "channel",
    "category": "Tech",
    "language": "pt",
    "members": 3226,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/manualdousuario",
    "source": "catalog",
    "live": false
  },
  {
    "username": "fortune",
    "title": "Fortune",
    "description": "Fortune lights the path for global leaders — and gives them the tools to make business better.",
    "type": "channel",
    "category": "Business",
    "language": "en",
    "members": 3077,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/fortune",
    "source": "catalog",
    "live": false
  },
  {
    "username": "macmagazine",
    "title": "MacMagazine",
    "description": "Receba no seu Telegram notificações de todos os posts do MacMagazine!",
    "type": "channel",
    "category": "Tech",
    "language": "pt",
    "members": 2702,
    "online": null,
    "verified": true,
    "photo": null,
    "link": "https://t.me/macmagazine",
    "source": "catalog",
    "live": false
  },
  {
    "username": "golang_ru",
    "title": "Golang Developers — русскоговорящее сообщество",
    "description": "Общаемся на тему разработки на Golang. Обсуждаем идеи и новости, решаем проблемы, учимся вместе. Вакансии и резюме: @golang_jobs См. также: @eth_ru , @nodejs_ru , @javascript_jobs",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 1637,
    "online": 363,
    "verified": false,
    "photo": null,
    "link": "https://t.me/golang_ru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "sciencenews",
    "title": "Science News",
    "description": "",
    "type": "channel",
    "category": "Science",
    "language": "en",
    "members": 1349,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/sciencenews",
    "source": "catalog",
    "live": false
  },
  {
    "username": "firebase",
    "title": "Firebase",
    "description": "All about Firebase. All about BigQuery: https://t.me/BigQuery",
    "type": "channel",
    "category": "Tech",
    "language": "en",
    "members": 1195,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/firebase",
    "source": "catalog",
    "live": false
  },
  {
    "username": "tensorflow",
    "title": "TensorFlow discuss group [en]",
    "description": "Learn together. Google/Stackoverflow is your friend. Chat in EN. Please don't spam here. If you want to promote your group/channel/website, behave like a human first.",
    "type": "group",
    "category": "Community",
    "language": "en",
    "members": 1089,
    "online": 69,
    "verified": false,
    "photo": null,
    "link": "https://t.me/tensorflow",
    "source": "catalog",
    "live": false
  },
  {
    "username": "dribbble",
    "title": "dribbble",
    "description": "dribbble.com",
    "type": "channel",
    "category": "Design",
    "language": "en",
    "members": 898,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/dribbble",
    "source": "catalog",
    "live": false
  },
  {
    "username": "astronomy",
    "title": "Astronomy",
    "description": "",
    "type": "channel",
    "category": "Science",
    "language": "en",
    "members": 617,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/astronomy",
    "source": "catalog",
    "live": false
  },
  {
    "username": "euronews_en",
    "title": "🇪🇺 Euronews English",
    "description": "",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 613,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/euronews_en",
    "source": "catalog",
    "live": false
  },
  {
    "username": "vuejs",
    "title": "Vue.js — 🧧 Global Community",
    "description": "Talk about vuejs",
    "type": "group",
    "category": "Community",
    "language": "en",
    "members": 563,
    "online": 39,
    "verified": false,
    "photo": null,
    "link": "https://t.me/vuejs",
    "source": "catalog",
    "live": false
  },
  {
    "username": "python_ru",
    "title": "Python Chat",
    "description": "Чат о Питоне",
    "type": "group",
    "category": "Community",
    "language": "ru",
    "members": 435,
    "online": 10,
    "verified": false,
    "photo": null,
    "link": "https://t.me/python_ru",
    "source": "catalog",
    "live": false
  },
  {
    "username": "propublica",
    "title": "ProPublica",
    "description": "RSS feed for ProPublica articles, replacing the bot that used to exist for it.",
    "type": "channel",
    "category": "News",
    "language": "en",
    "members": 415,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/propublica",
    "source": "catalog",
    "live": false
  },
  {
    "username": "lichess",
    "title": "lichess",
    "description": "",
    "type": "channel",
    "category": "Games",
    "language": "en",
    "members": 283,
    "online": null,
    "verified": false,
    "photo": null,
    "link": "https://t.me/lichess",
    "source": "catalog",
    "live": false
  },
  {
    "username": "supabase",
    "title": "Supabase",
    "description": "Build in a weekend. Scale to millions. Supabase is an open source Firebase alternative. Start your project with a Postgres Database, Authentication, instant APIs, Realtime subscriptions and Storage. chat rus @supabase_rus",
    "type": "group",
    "category": "Community",
    "language": "en",
    "members": 252,
    "online": 9,
    "verified": false,
    "photo": null,
    "link": "https://t.me/supabase",
    "source": "catalog",
    "live": false
  }
]
